services:
  - type: web
    name: aqylflow
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: 8799281877:AAHuImnbo4676epEZKKmRuMRR5skmR-0F2g
        sync: false
      - key: 622522768
        sync: false
